# baseURL = 'http://example.org/'
#languageCode = 'en-us'
#title = 'My New Hugo Site'

baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Drupalcamp Rennes 2024"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
cleanDestinationDir = true

[params]
images = ["img/og-image.jpg"]

